### ISSUE TITLE
Action fails with API failure

### ISSUE THREAD

**Issue by grantholle** [laukstein/do-spaces#2]
When running this in an action, everything is uploaded correctly, but fails for the action with this response:

```
Done. Uploaded 4349728 bytes in 20.6 seconds, 205.93 KB/s.
DigitalOcean CDN purge failed. API response:
{"id":"service_unavailable","message":"Failed to forward the request you made, please try again."}
```

My actions is:

```
- name: Upload frontend assets to DigitalOcean Spaces
  uses: laukstein/do-spaces@main
  env:
    DO_TOKEN: ${{ secrets.SPACES_TOKEN }}
    DO_ACCESS: ${{ secrets.SPACES_KEY }}
    DO_SECRET: ${{ secrets.SPACES_SECRET }}
    DO_NAME: ${{ secrets.SPACES_NAME }}
    DO_REGION: nyc3
    LOCAL_DIR: public/build
```
